# Experiment 2: Numerical Python (Numpy)
#### Name: Tiñana, Chelzy Gracel
#### Section: 2ECE-D

## NORMALIZATION PROBLEM
#### Normalization is one of the most basic preprocessing techniques in data analytics. This involves centering and scaling process. Centering means subtracting the data from the mean and scaling means dividing with its standard deviation. Mathematically, normalization can be expressed as: 

#### In Python, element-wise mean and element-wise standard deviation can be obtained by using .mean() and .std() calls

#### In this problem, create a 5x5 ndarray and store it to variable X. Normalize X. Save your ndarray as X_normalized.npy

In [53]:
import numpy as np

# Create a 5x5 ndarray and store to variable X.
X = np.random.randint(1,100, size=(5,5))
X

array([[11, 33, 41, 30, 96],
       [96, 58, 85, 21, 69],
       [98, 82, 38, 41, 42],
       [59, 31, 51, 43, 70],
       [31, 26, 65, 44,  2]])

In [119]:
# Calculate the mean of the ndArray.
mean = np.mean(X)

# Calculate the standard deviation of the ndArray.
stddev = np.std(X)

# Normalize the array
n = X - mean
X_normalized = n/stddev

print(X_normalized)

[[-1.51471044 -0.67150119 -0.36487964 -0.78648427  1.74314349]
 [ 1.74314349  0.28669115  1.32153886 -1.13143351  0.70829577]
 [ 1.81979888  1.20655578 -0.47986272 -0.36487964 -0.32655195]
 [ 0.32501884 -0.74815657  0.01839729 -0.28822425  0.74662346]
 [-0.74815657 -0.93979504  0.554985   -0.24989656 -1.85965968]]


## DIVISIBLE BY 3 PROBLEM
#### Create the following 10x10 ndarray A which are the squares of the first 100 positive integers. From this ndarray, determine all the elements that are divisible by 3. Save the result as div_by_3.npy

In [77]:
import numpy as np

# Generate the first 100 positive integers.
num = np.arange(1,101)

# Compute for the squares of each integer.
squaredNum = num**2

# Store the calculated squares in the 10x10 array.
A = squaredNum.reshape((10,10))

# 10x10 array of the first 100 positive integers.
print(A)

[[    1     4     9    16    25    36    49    64    81   100]
 [  121   144   169   196   225   256   289   324   361   400]
 [  441   484   529   576   625   676   729   784   841   900]
 [  961  1024  1089  1156  1225  1296  1369  1444  1521  1600]
 [ 1681  1764  1849  1936  2025  2116  2209  2304  2401  2500]
 [ 2601  2704  2809  2916  3025  3136  3249  3364  3481  3600]
 [ 3721  3844  3969  4096  4225  4356  4489  4624  4761  4900]
 [ 5041  5184  5329  5476  5625  5776  5929  6084  6241  6400]
 [ 6561  6724  6889  7056  7225  7396  7569  7744  7921  8100]
 [ 8281  8464  8649  8836  9025  9216  9409  9604  9801 10000]]


In [97]:
# Look for values that are divisible by 3.
multiplesOf3 = A % 3 == 0

# Results
div_by_3 = A[multiplesOf3]
print(div_by_3)

[   9   36   81  144  225  324  441  576  729  900 1089 1296 1521 1764
 2025 2304 2601 2916 3249 3600 3969 4356 4761 5184 5625 6084 6561 7056
 7569 8100 8649 9216 9801]
